### ISSUE TITLE
Novo Design para o README.md & Dica Especial

### ISSUE THREAD

**Issue by pglapds** [vuejs-br/empresas-que-usam-vue-no-brasil#173]
Usa Stackedit Markdown! Como? Acessa o site  e seleciona esse Markdown. Assim, você pode editar diretamente com o Stackedit e é melhor do que o Github.

Novo Design? Tables é feio e com muita informação pesa... Demorou para abrir... Rs... tenho a solução.

Outra coisa... seria interessante usar Json... assim alguém faz a mudança e compartilha um link para todo mundo.

**Comment by IgorHalfeld** [comment]
#174 done!
