### ISSUE TITLE
Empresa da lista não utiliza Vue

### ISSUE THREAD

**Issue by lucivaldo** [vuejs-br/empresas-que-usam-vue-no-brasil#182]
A empresa "O Boticário" não utiliza mais Vue em seu site. Ela está usando atualmente React.

**Comment by IgorHalfeld** [comment]
Hmm... consegue mandar um PR pra gente removendo?

**Comment by lucivaldo** [comment]
Não consigo. Clonei o repositório na minha máquina, criei um novo branch, fiz as alterações. Tentei o push com o novo branch mas dá permissão negada. Fiz o merge no master e tentei o push novamente mas dá permissão negada.

**Comment by lucivaldo** [comment]
É bom fazermos uma revisão se esses sites estão realmente utilizando Vue. Os caras estão começando a fazer artigos na internet zoando essa lista aqui, dizendo que quando vai fazer uma conferência, na primeira tentava esbarra em um site que não utiliza Vue, usa React. Eu mesmo me deparei com uns 5 dessa lista que não mais utilizam Vue, mas é bom fazermos uma checagem completa, ou que sabe, podemoso automatizar esse processo.

**Comment by IgorHalfeld** [comment]
Hmm. então
1. Sobre a permissão, você precisa fazer o fork e então fazer as alteração no seu fork, para depois fazer o PR, dá só um [visu aqui](https://www.digitalocean.com/community/tutorials/como-criar-um-pull-request-no-github-pt)

2. Sobre estar utilizando Vue ou não, infelizmente não conseguimos comprovar se esta ou não, acredito que  vamos ter que acreditar na honestidade da pessoa ao contribuir com um projeto open source =\

**Comment by xereda** [comment]
@lucivaldo Boa tarde caro Lucivaldo. 

Entendo que não há motivo para fazermos uma revisão da lista. Essa lista se auto regulamentará. Se fôssemos tratar da forma que você está sugerindo, não teríamos a Wikipédia.

O repositório não está fechado. Qualquer um que julgar que uma determinada empresa não deva estar aqui nessa lista, basta abrir um PR. 

Mas é necessário que o usuário conheça pelo menos o básico do fluxo de PR do github. Caso contrário, Lucivaldo, você não conseguirá sugerir alterações.

Agradeço a abertura da issue. 

Um abraço,

Jackson

**Comment by wilcorrea** [comment]
@lucivaldo você tem algum artigo pra nos indicar e entender o que está acontecendo? É um repositório público, não dá nem para saber onde é usada a tecnologia. Pode ser apenas num produto interno ou até mesmo num serviço que a empresa utiliza operacionalmente. Precisamos ir até as pessoas que estão "zoando" e explicar isso para eles = )

**Comment by wilcorrea** [comment]
Apenas para fins de esclarecimentos.
Este é o PR que inclui a empresa citada na lista https://github.com/vuejs-br/empresas-que-usam-vue-no-brasil/pull/113. Ele foi feito @felipe-ssilva. Ao que tudo indica o mesmo ainda está relacionado ao grupo (pelo menos é o que consta no linkedin dele https://www.linkedin.com/in/felipe-da-silva-b8664562/).

Logo, cabe ao @felipe-ssilva a decisão de manter ou remover a empresa da lista, ou de algum representante formal da empresa que corrija o posicionamento outrora informado = )

**Comment by ggondim** [comment]
Acho que se não está explícito no site da empresa que usam Vue, que seja pedido um case de sucesso da empresa com a tecnologia.

Nós da NOALVO, por exemplo, usamos Vue e estamos na lista, mas nosso site institucional ainda está em Angular. Mas divulgo o case do Vue em meetups e no Medium, seria legal colocar aqui também. 

Acho que realmente alguma demonstração de utilização a empresa tem que ter pra garantir a reputação dessa lista.

**Comment by lucivaldo** [comment]
Sobre o artigo que li e verifiquei isso é este: [https://medium.com/@milfont/tend%C3%AAncias-sobre-frameworks-javascript-em-2019-15369b2ad8cd](https://medium.com/@milfont/tend%C3%AAncias-sobre-frameworks-javascript-em-2019-15369b2ad8cd).

Mas eu entendi as regras deste repositório. Como o @wilcorrea comentou acima, somente os responsáveis pela PR de inclusão podem manter ou remover.

Só levantei a questão aqui porque pareceu conveniente. Realmente o site do Boticário não utiliza Vue, utiliza React. Mas entendi o posicionamento de vocês, embora seja questionável.

**Comment by lucivaldo** [comment]
> @lucivaldo Boa tarde caro Lucivaldo.
> 
> Entendo que não há motivo para fazermos uma revisão da lista. Essa lista se auto regulamentará. Se fôssemos tratar da forma que você está sugerindo, não teríamos a Wikipédia.
> 
> O repositório não está fechado. Qualquer um que julgar que uma determinada empresa não deva estar aqui nessa lista, basta abrir um PR.
> 
> Mas é necessário que o usuário conheça pelo menos o básico do fluxo de PR do github. Caso contrário, Lucivaldo, você não conseguirá sugerir alterações.
> 
> Agradeço a abertura da issue.
> 
> Um abraço,
> 
> Jackson
@xereda 

Eu entendo seu posicionamento. Mas acredito que é desproporcional comparar a manutenção do Wikipédia com esta lista. Esta lista tem cerca de 139 sites,  0,0138% do total de artigos **em Português** do Wikipédia.

Mas enfim, como falei anteriormente, só levantei a questão.

**Comment by wilcorrea** [comment]
Obrigado pelo link @lucivaldo 
Cara, assim, eu não conheço o autor e acredito que a opinião dele é boa! Concordo com ele que se o cara estiver procurando oportunidades de trabalho React é a bola da vez, jamais diria o contrário.. só que tem umas falhas na argumentação dele. Só para você ter uma ideia, [essa imagem](https://cdn-images-1.medium.com/max/1200/1*WXBLq55uNfDToj53zDYwyw.png) chega à ser engraçada, a extensão do Vue não reconhece o bundle de produção se você configurar isso (https://vuejs.org/v2/api/#devtools) o que é uma boa prática mínima para um desenvolvedor front-end. 

Agradeço (for real) sua iniciativa de ajudar o repositório, mas não podemos deliberadamente remover a contribuição do rapaz (o @felipe-ssilva no caso). O que me comprometo em fazer é colocar um disclaimer na lista para minimizar a desinformação que isso possa ter causado ; )

**Comment by IgorHalfeld** [comment]
Então, acho que entra no ponto que o @ggondim falou, a home da NOALVO ainda usa Angular 1.x
mas temos Vue internamente, por isso se torna difícil comprovar se realmente esta usando Vue.js
