### ISSUE TITLE
Sugestao para o readme

### ISSUE THREAD

**Issue by IgorDePaula** [vuejs-br/empresas-que-usam-vue-no-brasil#186]
Em se tratando de Brasil, eu sugeriria ordenar por estados e depois por empresa. Eu fui procurar por empresas do RIo de Janeiro e foi dificil encontrar.

**Comment by IgorHalfeld** [comment]
Mesmo procurando por `RJ` no `CTRL+F`?

**Comment by IgorHalfeld** [comment]
Na real, o ideal é que fosse tudo `json` e tivesse uma interface 🤣

**Comment by IgorDePaula** [comment]
Se eu tivesse so uma secao RJ eu acharia todas de uma vez =/

Mas posso pensar em algo pra ler esse readme e criar uma interface.

**Comment by kwekwwelkwelk** [comment]
> Na real, o ideal é que fosse tudo `json` e tivesse uma interface

Já fiz.

**Comment by kwekwwelkwelk** [comment]
> Na real, o ideal é que fosse tudo `json` e tivesse uma interface

**O que você acha? Pessoal, o que vocês acham?** 

![1](https://user-images.githubusercontent.com/46846354/61674962-a3079600-accc-11e9-8d6f-a20ced4ce724.png)

**Comment by kwekwwelkwelk** [comment]
> Se eu tivesse so uma secao RJ eu acharia todas de uma vez =/
> 
> Mas posso pensar em algo pra ler esse readme e criar uma interface.

Legal.

**Comment by kwekwwelkwelk** [comment]
> Na real, o ideal é que fosse tudo `json` e tivesse uma interface

Já fiz. Acesse: https://github.com/kwekwwelkwelk/encontre1/blob/master/v_data/json/src/pt-br/encontre.json

**Comment by kwekwwelkwelk** [comment]
Versão 2. 

![V2](https://user-images.githubusercontent.com/46846354/61816987-dc9ee500-ae23-11e9-9134-58efc7ba52d6.png)

**Comment by Renato66** [comment]
Galera https://empresas-que-usam-vue.netlify.com

**Comment by IgorHalfeld** [comment]
@Renato66 WOW, QUE INSANO CARA, parabéns!!

**Comment by IgorHalfeld** [comment]
Manda um PR pra gente disso aí, que eu consigo habilitar o netlify pra esse repo aqui.
Aí o pessoal ainda continua mandando adição de empresa pelo README, mas a galera vê na interface :D

**Comment by wilcorrea** [comment]
Acredito que este tópico esteja ok, caso julguem necessário reabrimos :kiss:
