### ISSUE TITLE
[Site] Binding dos filtros na URL

### ISSUE THREAD

**Issue by emanuelgsouza** [vuejs-br/empresas-que-usam-vue-no-brasil#231]
Implementar *binding* dos dados dos filtros para a URL, permitindo assim que seja possível compartilhar uma URL com determinado filtro

**Comment by GuiDevloper** [comment]
Com essa PR aí, agora pode mandar um link assim pro amigo ou amiga afim de mostrar empresas em tais parâmetros rapidamente:

https://empresas-usando-vuejs.netlify.app/?tags=Vuex,Node,Axios,React&name=olx&location=são+paulo&remote=true
