### ISSUE TITLE
[repos] Adicionar índice

### ISSUE THREAD

**Issue by martygo** [vuejs-br/empresas-que-usam-vue-no-brasil#281]
A minha sugestão é de que teria um indíce alfabeto para caso a pessoa simplesmente queira procurar empresas de acordo com uma letra aqui no repositório.

**Comment by GuiDevloper** [comment]
Interessante, @martygo.

Me lembrou que naturalmente são criados índices pela divisão que a lista já tem, então isso aqui já é possível e pode ajudar muito nisso:
(Exemplo indo direto na letra S)
https://github.com/vuejs-br/empresas-que-usam-vue-no-brasil#s

**Comment by martygo** [comment]
Muito bom 😊.

Em terça-feira, 23 de novembro de 2021, Guilherme Correia <
***@***.***> escreveu:
